In [27]:
import pandas as pd
import numpy as np

In [30]:
age = np.array([21, 20, 22, 22, 23, 21, 25, 30, 31])
Income = np.array([60, 55, 60, 61, 65, 62, 65, 70, 68])

In [33]:
df = pd.DataFrame({"age" : age, "Income" : Income})

In [34]:
df

age  Income
0   21      60
1   20      55
2   22      60
3   22      61
4   23      65
5   21      62
6   25      65
7   30      70
8   31      68

## Task 01:Your objective is to implement the K-Nearest Neighbors (KNN) algorithm with k=3. Use this algorithm to predict the income value, with the given input value X=22.

In [35]:
from sklearn.neighbors import KNeighborsRegressor

In [36]:
neighbr = KNeighborsRegressor(n_neighbors=3)

In [38]:
neighbr.fit(df[['age']], df['Income'])

KNeighborsRegressor(n_neighbors=3)

In [40]:
neighbr.predict(df[['age']])

array([59.        , 59.        , 60.33333333, 60.33333333, 62.        ,
       59.        , 63.33333333, 67.66666667, 67.66666667])

In [41]:
neighbr.predict([[22]])

C:\Users\User\anaconda3\Lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but KNeighborsRegressor was fitted with feature names
  warnings.warn(


array([60.33333333])

In [43]:
neighbr.score(df[['age']], df['Income'])

0.7401315789473687

In [45]:
y_pred1 = neighbr.predict(df[['age']])

In [46]:
y_pred1

array([59.        , 59.        , 60.33333333, 60.33333333, 62.        ,
       59.        , 63.33333333, 67.66666667, 67.66666667])

In [47]:
df['y_pred1'] = neighbr.predict(df[['age']])

In [48]:
df

age  Income    y_pred1
0   21      60  59.000000
1   20      55  59.000000
2   22      60  60.333333
3   22      61  60.333333
4   23      65  62.000000
5   21      62  59.000000
6   25      65  63.333333
7   30      70  67.666667
8   31      68  67.666667

In [49]:
from sklearn.metrics import mean_squared_error

In [50]:
mse_knn = mean_squared_error(df['Income'], df['y_pred1'])

In [51]:
mse_knn

4.876543209876539

## Linear Regression

In [52]:
from sklearn.linear_model import LinearRegression

In [53]:
Age = np.array([21, 20, 22, 22, 23, 21, 25, 30, 31])
income = np.array([60, 55, 60, 61, 65, 62, 65, 70, 68])

In [54]:
df2 = pd.DataFrame({"Age" : Age, "income" : income})

In [55]:
df2

Age  income
0   21      60
1   20      55
2   22      60
3   22      61
4   23      65
5   21      62
6   25      65
7   30      70
8   31      68

In [56]:
model = LinearRegression()

In [57]:
model.fit(df2[['Age']], df2['income'])

LinearRegression()

In [58]:
model.predict([[22]])

C:\Users\User\anaconda3\Lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([60.97068966])

In [59]:
y_pred2 = model.predict(df2[['Age']])

In [60]:
y_pred2

array([59.95517241, 58.93965517, 60.97068966, 60.97068966, 61.9862069 ,
       59.95517241, 64.01724138, 69.09482759, 70.11034483])

In [61]:
df2['y_pred2'] = model.predict(df2[['Age']])

In [62]:
df2

Age  income    y_pred2
0   21      60  59.955172
1   20      55  58.939655
2   22      60  60.970690
3   22      61  60.970690
4   23      65  61.986207
5   21      62  59.955172
6   25      65  64.017241
7   30      70  69.094828
8   31      68  70.110345

In [63]:
model.score(df2[['Age']], df2['income'])

0.7870258620689655

In [64]:
mse_lr = mean_squared_error(df2['income'], df2['y_pred2'])

In [65]:
mse_lr

3.996551724137931

Applying KNN, achieved accuracy of 74%. On the other hand applying Linear Regression, achieved accuracy of 78%. So, If we compare both algorithm we get less MSE in Linear Reagression than KNN.

## Final Task: Generate an Excel spreadsheet for a provided dataset.

In [67]:
filename = 'age-income.xlsx'
given_df = df[['age', 'Income']]
given_df.to_excel(filename)